version: '3.8'

services:
  db_rtapp:
    image: postgres:14.2
    container_name: rtapp_pg
    ports:
      - 3003:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
      - ./db:/db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=rtapp_db
      - PGDATA=/var/lib/postgresql/data/pgdata

  app_rtapp:
    build: ./
    container_name: rtapp_app
    ports:
      - 4321:4321